---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Holy Quiche!"
keywords:    "Quiche French Farmers Market LA Los Angeles"
description: "Find us at your favorite Farmers Market in Los Angeles or call us for special orders and deliveries."
source_link: "https://github.com/holyquiche/holyquiche.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: 


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

sass:
  style: compressed

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
